version: 2.1
jobs:
  configure_project:
    docker: 
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Show OS version
          command: |
            if [ -e /etc/os-release ]; then
              cat /etc/os-release
            elif [ -e /etc/redhat-release ]; then
              cat /etc/redhat-release
            else
              echo 'Invalid Image' 1>&2
              exit 1
            fi
      - add_ssh_keys:
          fingerprints: ["59:ed:c0:fb:af:97:29:44:39:ec:39:a1:66:bf:c3:7b"]
      - run:
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: Show Ansible version
          command: ansible --version
      - run:
          name: configure and run ansible playbook
          command: |
            ansible-playbook -vvv -i inventory.txt playbook.yml 
  cleanup_server:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: clean up server using ansible
          command: |
            ansible-playbook -vvv -i inventory.txt cleanup.yml
  
workflows:
  deployment_workflow:
    jobs:
      - configure_project
      - cleanup_server:
          requires:
            - configure_project
