version: 2.1
jobs:
  configure_project:
    docker: 
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["c0:04:eb:73:a2:84:bd:ad:9a:37:aa:1f:2b:07:8d:50"]
      - run:
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: configure and run ansible playbook
          command: |
            ansible-playbook -i inventory.txt playbook.yml 
  
workflows:
  deployment_workflow:
    jobs:
      - configure_project
